### ISSUE TITLE
Have default YAML specification created with "default" title

### ISSUE THREAD

**Issue by simplesagar** [speakeasy-api/cli#10]
Slack: https://speakeasyapi.slack.com/archives/C03BEMS60GZ/p1652135697230919

Acceptance Criteria: 
- Running `api init` on a service with no annotations results in a default specification that looks like the following: 

```
components: {}
externalDocs: {}
info:
  contact: {}
  description: '@description'
  license:
    name: ""
  title: default
  version: 
openapi: "3.0"
paths: {}
```

**Comment by simplesagar** [comment]
https://speakeasyapi.slack.com/archives/C03BEMS60GZ/p1652810169460469

**Comment by r-shanahan** [comment]
This is resolved!
