### ISSUE TITLE
Responses Section of schema incorrectly generated 

### ISSUE THREAD

**Issue by simplesagar** [speakeasy-api/cli#3]
slack: https://speakeasyapi.slack.com/archives/C03BEMS60GZ/p1651177994656739

YAML generated: there is a bug in the responses section; no matter what i annotate as the response its name is always `E`.

Acceptance Criteria: 
- Response section includes the complete OpenAPI3.0 Model for `Response` with no offending characters

**Comment by r-shanahan** [comment]
![image](https://user-images.githubusercontent.com/93939862/166302245-fdcb3ad4-5fa5-4100-b453-4c164de8f46c.png)
 
here is another picture of an example spec generation.

**Comment by simplesagar** [comment]
This but is still open see : https://speakeasyapi.slack.com/archives/C03BEMS60GZ/p1652809509278389

``
responses:
  È:
    content:
      application/json:
        schema:
          type: body
    description: OK
summary: Fetch a Statement.
```

is what I get when adding in the annotation for the response, either for a string or object.
annotation: `// @Success 200 {body} api_json_views.MerchantStatementView` gives the above. This also happens if i change the response to just a string. (edited)
